# Generated by Django 4.2.6 on 2023-10-20 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 10, 21, 0, 14, 43, 582393))),
                ('payment_date', models.DateTimeField(default=datetime.datetime(2023, 10, 21, 0, 14, 43, 582393))),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
    ]
