# Generated by Django 4.2.6 on 2023-10-23 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status_alter_order_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 17, 27, 36, 6520)),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 17, 27, 36, 6520)),
        ),
    ]
